{% set name = "kissim" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 7d02bd7c8afccd39ef93a86fd0657aff9e040808e59205ba88aef34cdb18d5cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kissim = kissim.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - scipy
    - matplotlib-base
    - jupyter
    - jupyterlab
    - ipywidgets
    - nglview
    - biopython <=1.77
    - opencadd

test:
  imports:
    - kissim
  commands:
    - kissim -h

about:
  home: https://github.com/volkamerlab/kissim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Subpocket-based fingerprint for kinase pocket comparison
  description: |
    Subpocket-based fingerprint for kinase pocket comparison
  doc_url: https://kissim.readthedocs.io/
  dev_url: https://github.com/volkamerlab/kissim

extra:
  recipe-maintainers:
    - dominiquesydow
    - AndreaVolkamer
